site_name: QuantFlow
site_url: https://quantmind.github.io/quantflow/
site_dir: app/docs
repo_name: quantmind/quantflow
repo_url: https://github.com/quantmind/quantflow
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - content.code.copy
  logo: assets/quantflow-logo.png
  favicon: img/favicon.png
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters:
              - "!^_[a-zA-Z0-9_]*"
              - "!^model_post_init$"
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            extensions:
              - griffe_typingdoc
              - griffe_pydantic:
                  schema: false
nav:
  - Home: index.md
  - Examples:
      - Gaussian Sampling: examples/gaussian-sampling
      - Poisson Sampling: examples/poisson-sampling
      - Double Exponential Sampling: examples/double-exponential-sampling
      - Hurst: examples/hurst
      - Supersmoother: examples/supersmoother
  - API Reference:
      - api/index.md
      - Data:
          - api/data/index.md
          - Deribit: api/data/deribit.md
          - Federal Reserve: api/data/fed.md
          - Financial Modeling Prep: api/data/fmp.md
          - FRED: api/data/fred.md
      - Options:
          - api/options/index.md
          - Black-Scholes: api/options/black.md
          - Calibration: api/options/calibration.md
          - Pricer: api/options/pricer.md
          - Volatility Surface: api/options/vol_surface.md
      - Stochastic Processes:
          - api/sp/index.md
          - CIR Process: api/sp/cir.md
          - Compound Poisson: api/sp/compound_poisson.md
          - Heston Model: api/sp/heston.md
          - Jump Diffusion: api/sp/jump_diffusion.md
          - Ornstein-Uhlenbeck: api/sp/ou.md
          - Poisson Process: api/sp/poisson.md
          - Weiner Process: api/sp/weiner.md
      - Technical Analysis:
          - api/ta/index.md
          - EWMA: api/ta/ewma.md
          - Kalman Filter: api/ta/kalman.md
          - OHLC: api/ta/ohlc.md
          - Paths: api/ta/paths.md
          - Supersmoother: api/ta/supersmoother.md
      - Utilities:
          - api/utils/index.md
          - Bins: api/utils/bins.md
          - Distributions: api/utils/distributions.md
          - Marginal 1D: api/utils/marginal1d.md
  - Contributing: contributing.md
  - Bibliography: bibliography.md
markdown_extensions:
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
