name: Docker Multi-arch Build

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: install rops
        run: |
          curl -L https://raw.githubusercontent.com/quantmind/rops/main/dev/install-rops | bash
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: build amd64
        run: DOCKER_BUILDKIT=0 docker build . -f dev/quantflow.dockerfile -t ${{ inputs.image-name }}:${{ github.sha }}-amd64
      - name: push amd64
        run: docker push ${{ inputs.image-name }}:${{ github.sha }}-amd64

  build-arm64:
    runs-on: ubuntu-24.04-arm
    env:
      GITHUB_TOKEN: ${{ github.token }}
      DOCKER_BUILDKIT: 0

    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: install rops
        run: |
          curl -L https://raw.githubusercontent.com/quantmind/rops/main/dev/install-rops | bash
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: build arm64
        run: DOCKER_BUILDKIT=0 docker build . -f dev/quantflow.dockerfile -t ${{ inputs.image-name }}:${{ github.sha }}-arm64
      - name: push arm64
        run: docker push ${{ inputs.image-name }}:${{ github.sha }}-arm64

  manifest:
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: install rops
        run: |
          curl -L https://raw.githubusercontent.com/quantmind/rops/main/dev/install-rops | bash
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: create manifest
        run: docker manifest create ${{ inputs.image-name }}
