name: Docker Multi-arch Build

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: install rops
        uses: quantmind/rops/.github/actions/setup-rops@main
      - name: build amd64
        run: rops docker build ${{ inputs.image-name }}
      - name: push amd64
        run: rops docker push ${{ inputs.image-name }} --arch

  build-arm64:
    runs-on: ubuntu-24.04-arm
    env:
      GITHUB_TOKEN: ${{ github.token }}
      DOCKER_BUILDKIT: 0

    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: install rops
        uses: quantmind/rops/.github/actions/setup-rops@main
      - name: build arm64
        run: rops docker build ${{ inputs.image-name }}
      - name: push arm64
        run: rops docker push ${{ inputs.image-name }} --arch

  manifest:
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: install rops
        uses: quantmind/rops/.github/actions/setup-rops@main
      - name: create manifest
        run: rops docker manifest ${{ inputs.image-name }}
